name: nomads_tour
description: "Application for tourists"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  latlong2: ^0.9.0
  flutter_polyline_points: ^2.1.0

  cloud_firestore: ^4.9.0
  firebase_core: ^2.30.0
  firebase_core_web: ^2.13.0
  firebase_storage_web: ^3.7.0
  firebase_storage: ^11.6.4

  image_picker: ^1.0.4
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/blog/