// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyvOOk_0pB-P5lfq-TqUntfoeK-nguyMc',
    appId: '1:950595416475:web:f7ed93f73b064731cef13e',
    messagingSenderId: '950595416475',
    projectId: 'nomadstour-cc29c',
    authDomain: 'nomadstour-cc29c.firebaseapp.com',
    storageBucket: 'nomadstour-cc29c.firebasestorage.app',
    measurementId: 'G-LB98G6W5WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWJxkxjv-3-UEd0vupYqNuFhsfU0t3IeE',
    appId: '1:950595416475:android:5361d87e3b7cdf99cef13e',
    messagingSenderId: '950595416475',
    projectId: 'nomadstour-cc29c',
    storageBucket: 'nomadstour-cc29c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5mL4jpcJB3za5FrZdkZVph2A3WJrG8_4',
    appId: '1:950595416475:ios:88e5ae10fc5f2a53cef13e',
    messagingSenderId: '950595416475',
    projectId: 'nomadstour-cc29c',
    storageBucket: 'nomadstour-cc29c.firebasestorage.app',
    iosBundleId: 'com.example.nomadsTour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5mL4jpcJB3za5FrZdkZVph2A3WJrG8_4',
    appId: '1:950595416475:ios:88e5ae10fc5f2a53cef13e',
    messagingSenderId: '950595416475',
    projectId: 'nomadstour-cc29c',
    storageBucket: 'nomadstour-cc29c.firebasestorage.app',
    iosBundleId: 'com.example.nomadsTour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyvOOk_0pB-P5lfq-TqUntfoeK-nguyMc',
    appId: '1:950595416475:web:90bdd50e183da875cef13e',
    messagingSenderId: '950595416475',
    projectId: 'nomadstour-cc29c',
    authDomain: 'nomadstour-cc29c.firebaseapp.com',
    storageBucket: 'nomadstour-cc29c.firebasestorage.app',
    measurementId: 'G-D00LVVMWBD',
  );
}
